### ISSUE TITLE
support request for `text` version >= 2

### ISSUE THREAD

**Issue by peterbecich** [typeclasses/chell#2]
This would assist building the library with Nix.

Thank you

**Comment by chris-martin** [comment]
I am having some difficulty upgrading things because of these dependencies:

`chell` → `options` → `monads-tf` → `transformers <0.6`

I've forked and updated [monads-tf](https://github.com/typeclasses/monads-tf) and sent an email to the maintainer (Ross Paterson) to inquire about getting the changes released.

Alternatively, it might also be a good idea to removed the `options` dependency and replace it with `optparse-applicative`, if anybody were interested in doing that work.

**Comment by chris-martin** [comment]
`monads-tf-0.3.*` now builds with the latest dependencies. Sent another email (John Millikin) to inquire about taking over the [options](https://hackage.haskell.org/package/options) package.

**Comment by chris-martin** [comment]
Acquired ownership of the `options` package, and released `options-1.2.1.2`.

So that's enough for the `chell` packages to build with the latest stuff now.

Releases:

- `chell-0.5.0.2`
- `chell-hunit-0.3.0.2`
- `chell-quickcheck-0.2.5.4`
